### ISSUE TITLE
Help to install your app

### ISSUE THREAD

**Issue by tutsisback** [Minims/SomfyProtect2MQTT#1]
Hi Minims,

I've been browsing the web to find a solution to manage my Somfy Alarm from Home Assistant (I saw your name many times on forums) and I'm glad to see that you began to work on something.

I would love to help you (as an end user) to debug and/or improve your app.

I have really basic knowledge in dev so I need a bit of explanation to go further. Is it possible to detail steps to install your app ?

Just to let you know, I started using HA a few month ago, it's running on a raspb3, mqtt broker is already set up and used through Node Red to drive Ikea spotlights and sonoff relay (garage door).

By the way I assume you speak french or even you're french ? I'm also french ;)

One more thing, I saw that something is on going on Jeedom's community side (an other french is building a plugin), don't know if it can be ported or at least help you... 

[https://community.jeedom.com/t/plugin-somfy-home-alarm-script-a-convertir-en-plugin/36119/31](https://community.jeedom.com/t/plugin-somfy-home-alarm-script-a-convertir-en-plugin/36119/31)

**Comment by Minims** [comment]
Hi,

I'm still at the beginning of the app. I hope a can go further. 
I'm working on device settings, like IntelliTag sensibility or manage siren notification for example. 
This part seems working.

For the installation of my app.
You need a raspbian or Debian virtual machine. It can works in a Docker too.

This member has setup an integration for HA with Docker for ie : 
https://github.com/schumijo/homeassistant-addons/

On a Debian/Raspbian : 

```
sudo apt install python3 git python3-pip
git clone https://github.com/Minims/SomfyProtect2MQTT
git checkout dev
cd SomfyProtect2MQTT
pip3 install -r  somfyProtect2Mqtt/requirements.txt
cd somfyProtect2Mqtt
# Edit file config/config.yaml with your credentials and site in Somfy and MQTT part
python3 main.py
```

If you use HA and have activate MQTT with discovery mode, all devices will appears automatically.

If You Have HA OS, you can add this repo as a custom repo on Supervisor AddOn :  https://github.com/schumijo/homeassistant-addons/

It will run in a Docker inside HA OS. It's the easier way for now.

Yes I'm French like most of the Home Alarm Users.

This Integration on jeedom seems great too. Would love to find source code.

**Comment by tutsisback** [comment]
Hi,

I've been able to install the addon made by shumijo and arm and disarmed the alarm from lovelace dashboard 👍 


Here is a bit of explanation regarding yaml config file : 

somfy_protect:
  username: "your_somfy_api_username"
  password: "your_somfy_api_password"
  sites:
    - "the_name_of_your_installation_as_it_is_written_in_your_somfy_app"
mqtt:
  host: "ip_adress_of_your_HA_mqtt_broker"
  port: '1883'
  username: "username_of_your_HA_mqtt_broker"
  password: "password_of_your_HA_mqtt_broker"
  client-id: somfy-protect
  topic_prefix: somfyProtect2mqtt
  ha_discover_prefix: homeassistant
delay_site: '10'
delay_device: '60'

**Comment by peluho** [comment]
Hi there,

thank your for all your effort. I was  trying to make this integration work. However I must be doing something wrong.
MQTT is up and working, I installed you add-on, then start it... however after several seconds it stops
I'm pretty sure is due to the configuration, but not sure what I'm doing wrong
`somfy_protect:
  username: xxxxxx@yyyyy.com (edited)
  password: yyyyy (edited)
  sites:
    - Home
homeassistant_config:
  code: false
  code_arm_required: false
  code_disarm_required: false
mqtt:
  host: 192.168.X.X (EDITED) 
  port: 1883
  ssl: false
  username: mqttbroker
  password: xxxxxxx (EDITED)
  client-id: somfy-protect
  topic_prefix: somfyProtect2mqtt
  ha_discover_prefix: homeassistant
delay_site: "10"
delay_device: "60"
manual_snapshot: false
debug: false`

Maybe the log is helping to know what's going on:

`Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:124
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 2:30:26 PM (3 occurrences)
Last logged: 3:08:30 PM

Failed to to call /addons/dfd2619f_somfy-protect-2-mqtt/stats - Container addon_dfd2619f_somfy-protect-2-mqtt is not running`

Thank you very much,

again

**Comment by Minims** [comment]
This logs is not the one of the add-on.
Try set code to : `0000`
and check the logs on the tab with the same name in the add-on panel
